Second deliverable

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,3 +67,20 @@ jobs:
         rm sales_tax_rate/sales_tax_rate.pid
         kill -9 `cat order_total/order_total.pid`
         rm order_total/order_total.pid
+
+
+    - name: test2
+      run: |
+        sleep 15
+        resp=$(curl http://localhost:8002/compute -X POST -d @order2.json)
+        echo "$resp"
+        if [[ $resp == *"\"status\": \"error\""* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        kill -9 `cat sales_tax_rate/sales_tax_rate.pid`
+        rm sales_tax_rate/sales_tax_rate.pid
+        kill -9 `cat order_total/order_total.pid`
+        rm order_total/order_total.pid
